image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- before: npm i -g gatsby-cli && git pull
  init: npm install
  command: gatsby develop

ports:
  - port: 8000
    onOpen: open-preview
